version: "3"
services:
  amazon-braket:
    image: aws-amazon-braket
    container_name: aws-braket-container
    build:
      context: ./
      dockerfile: ./Dockerfile # production environment
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - JUPYTER_ENABLE_LAB=yes
    volumes:
      - ./src:/home/braket/src
      - $HOME/.aws/:/home/braket/.aws/:ro
    ports:
      - 8339:8889
    restart: unless-stopped
    tty: true
