AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"
Description: An AWS Serverless Specification template describing your function.
Resources:
  blogtest1:
    Type: "AWS::Serverless::Function"
    Properties:
      Runtime: python3.9
      Description: ""
      CodeUri: ./src
      Handler: lambda_function.lambda_handler
      MemorySize: 128
      Timeout: 20
